name: Pages (prod, beta, PR previews)

on:
  push:
    branches: [ main, next, Next ]
  pull_request:
    branches: [ main, next, Next ]
    types: [opened, synchronize, reopened, ready_for_review, closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pages-${{ github.workflow }}-${{ github.ref || format('pr-{0}', github.event.number) }}
  cancel-in-progress: true

jobs:
  # --- PROD: push sur main -> racine de gh-pages ---
  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Optionnel: si tu as des dossiers commençant par "_" :
      - run: touch .nojekyll
      - name: Deploy production to gh-pages root
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          keep_files: true        # on préserve /beta et /pr-*

  # --- BÊTA: push sur next|Next -> gh-pages/beta ---
  deploy-beta:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/next' || github.ref == 'refs/heads/Next')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: touch .nojekyll
      - name: Deploy beta to gh-pages/beta
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          destination_dir: beta
          keep_files: true

  # --- PR PREVIEW vers Next: gh-pages/beta/pr-<num>/ ---
  pr-preview-next:
    if: github.event_name == 'pull_request' && (github.base_ref == 'next' || github.base_ref == 'Next') && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: touch .nojekyll
      - name: Deploy PR preview (Next)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          destination_dir: beta/pr-${{ github.event.number }}
          keep_files: true
      - name: Compute repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Comment preview URL (Next)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            🚀 Préversion déployée :
            https://${{ github.repository_owner }}.github.io/${{ env.REPO_NAME }}/beta/pr-${{ github.event.number }}/

  # --- PR PREVIEW vers main: gh-pages/pr-<num>/ ---
  pr-preview-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: touch .nojekyll
      - name: Deploy PR preview (main)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          destination_dir: pr-${{ github.event.number }}
          keep_files: true
      - name: Compute repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Comment preview URL (main)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            🚀 Préversion déployée :
            https://${{ github.repository_owner }}.github.io/${{ env.REPO_NAME }}/pr-${{ github.event.number }}/

  # --- CLEANUP: quand la PR est close/mergée, on supprime son dossier ---
  cleanup-preview:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Remove preview folder
        run: |
          set -eux
          rm -rf "pr-${{ github.event.number }}" "beta/pr-${{ github.event.number }}" || true
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: cleanup preview for PR #${{ github.event.number }}" || echo "Nothing to clean"
          git push
