name: Pages (prod + PR previews + beta + releases)

on:
  push:
    branches: [ main, next ]          # prod=main, beta=next
    tags: ['v*', 'v*.*', 'v*.*.*']    # releases/vX[.Y[.Z]]
  pull_request:                        # previews pour PR vers main/next
    branches: [ main, next ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifact layout
        shell: bash
        run: |
          set -e
          mkdir -p dist
          EXCLUDES="--exclude .git --exclude .github --exclude dist --exclude node_modules"

          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            rsync -a $EXCLUDES ./ dist/                     # preview éphémère
          elif [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            rsync -a $EXCLUDES ./ dist/                     # prod à la racine
          elif [ "${GITHUB_REF}" = "refs/heads/next" ]; then
            mkdir -p dist/beta && rsync -a $EXCLUDES ./ dist/beta/
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mkdir -p "dist/releases/${GITHUB_REF_NAME}"
            rsync -a $EXCLUDES ./ "dist/releases/${GITHUB_REF_NAME}/"
          else
            rsync -a $EXCLUDES ./ dist/
          fi

          touch dist/.nojekyll

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  preview:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
